-- Create Site Settings Table
create table public.site_settings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  maintenance_mode boolean default false,
  site_title text default 'Rizki Okan Saputra',
  contact_email text
);

-- Enable RLS
alter table public.site_settings enable row level security;

-- Policies
-- Allow anyone to read settings (needed for maintenance check)
create policy "Enable read access for all users" on public.site_settings
  for select using (true);

-- Allow only admin to update
create policy "Enable update for authenticated users only" on public.site_settings
  for update using (auth.role() = 'authenticated');

-- Insert default row (ID 1)
insert into public.site_settings (maintenance_mode, site_title)
values (false, 'Rizki Okan Saputra');
