-- ==========================================
-- Supabase Setup Script (Consolidated)
-- Includes: Projects, Certificates, Storage, Site Settings
-- ==========================================

-- 1. Projects Table
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  tech_stack text[] default '{}'::text[],
  demo_url text,
  repo_url text,
  image_url text,
  category text default 'Web App'::text
);
alter table public.projects enable row level security;

-- 2. Certificates Table
create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  issuer text,
  date text,
  credential_url text,
  image_url text
);
alter table public.certificates enable row level security;

-- 3. Site Settings Table
create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  maintenance_mode boolean default false,
  site_title text default 'Rizki Okan Saputra',
  contact_email text
);
alter table public.site_settings enable row level security;

-- Insert default settings if not exists
insert into public.site_settings (id, maintenance_mode, site_title)
values (1, false, 'Rizki Okan Saputra')
on conflict (id) do nothing;

-- 4. Storage Bucket (Portfolio Images)
insert into storage.buckets (id, name, public) 
values ('portfolio-images', 'portfolio-images', true)
on conflict (id) do nothing;

-- ==========================================
-- Row Level Security (RLS) Policies
-- ==========================================

-- Projects Policies
create policy "Public Read Projects" on public.projects for select using (true);
create policy "Admin Insert Projects" on public.projects for insert with check (auth.role() = 'authenticated');
create policy "Admin Update Projects" on public.projects for update using (auth.role() = 'authenticated');
create policy "Admin Delete Projects" on public.projects for delete using (auth.role() = 'authenticated');

-- Certificates Policies
create policy "Public Read Certificates" on public.certificates for select using (true);
create policy "Admin Insert Certificates" on public.certificates for insert with check (auth.role() = 'authenticated');
create policy "Admin Update Certificates" on public.certificates for update using (auth.role() = 'authenticated');
create policy "Admin Delete Certificates" on public.certificates for delete using (auth.role() = 'authenticated');

-- Site Settings Policies
create policy "Public Read Settings" on public.site_settings for select using (true);
create policy "Admin Update Settings" on public.site_settings for update using (auth.role() = 'authenticated');

-- Storage Policies
create policy "Public Read Images" on storage.objects for select using ( bucket_id = 'portfolio-images' );
create policy "Admin Upload Images" on storage.objects for insert with check ( bucket_id = 'portfolio-images' and auth.role() = 'authenticated' );
create policy "Admin Update Images" on storage.objects for update using ( bucket_id = 'portfolio-images' and auth.role() = 'authenticated' );
create policy "Admin Delete Images" on storage.objects for delete using ( bucket_id = 'portfolio-images' and auth.role() = 'authenticated' );
